name: Build Sibernetic

on:
  push:
    branches: [ master, dev*, ow* ]
  pull_request:
    branches: [ master, dev, ow* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7 ]
        runs-on: [ ubuntu-18.04 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install Intel OpenCL libraries needed for Sibernetic
      run: |

        # Based on: https://github.com/openworm/OpenWorm/blob/master/Dockerfile

        mkdir intel-opencl-tmp
        cd intel-opencl-tmp
        mkdir intel-opencl
        wget https://github.com/openworm/OpenWorm/raw/dev_inte/SRB5.0_linux64.zip
        unzip SRB5.0_linux64.zip
        tar -C intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
        sudo cp -R intel-opencl/* /
        sudo ldconfig
        cd ..
        sudo rm -r intel-opencl-tmp

        sudo cp -R /opt/intel/opencl/include/CL /usr/include/
        sudo apt install -y ocl-icd-opencl-dev vim

    - name: Build Sibernetic
      run: |

        sudo apt install -y python3.7-dev freeglut3-dev libglu1-mesa-dev
        sudo apt info libc-bin
        sudo apt install -y libc-bin=2.27-3ubuntu1.5
        python -V
        ls -alt
        make clean
        make

    - name: Run quick Sibernetic test
      run: |

        ./Release/Sibernetic -no_g timelimit=0.001

    - name: Final version info
      run: |

        python -V
        pip list
